### ISSUE TITLE
Limit concurrency of zonal statistics jobs

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-backend#228]
Currently, if a single user requests zonal statistics for 3 years worth of daily data, that will fire off more than 1000 Lambda executions at the exact same time. 1000 is the default global account limit of concurrent requests. We can easily increase that (we just requested 10k, just in case), but such a massive concurrent execution is probably not a good idea.

We need to address this programmatically - even when a user sends off a request like this, it should get rejected (gracefully) by the API. Maybe we can also reduce concurrency in the backend by limiting the number of "workers" that handle the per-file extraction jobs?

As @amarouane-ABDELHAK pointed out, another guardrail to put on could be to limit the number of concurrent Lambda executions for the worker Lambda, if that is possible. That way, executions of this particular function will not be able to exhaust the global account limit.

## Acceptance criteria

- [x] Created tickets in relevant projects to address this challenge and linked them here
- [x] Limited concurrency in one and/or another way

**Comment by j08lue** [comment]
Already discussed a bit with @vincentsarago here https://github.com/NASA-IMPACT/veda-ui/issues/660#issuecomment-1727352060

**Comment by amarouane-ABDELHAK** [comment]
I’m still examining the concurrent Lambda executions, and it appears that we should be in good shape. The rasterapi Lambda function processing duration is super short (10 ms when it is warm).
I even attempted to submit 26,000 requests in parallel, but it seems that only 100 concurrent executions were triggered ( I believe this behavior is probably because of Lambda’s automatic queuing mechanism).
![image (1)](https://github.com/NASA-IMPACT/veda-backend/assets/33136280/f11a8cb7-c321-4e32-97c1-410ea7251f95)
![image](https://github.com/NASA-IMPACT/veda-backend/assets/33136280/1ceb7b8e-b73c-4388-a56f-91a98de61411)

**Comment by vincentsarago** [comment]
@j08lue looking back at this I think I misunderstood the original issue. This is not related to titiler-pgstac but more a frontend (allowing the user such a big interval) / backend configuration (number of concurrent lambda as pointed but @amarouane-ABDELHAK) issue.

**Comment by j08lue** [comment]
Limits implemented in FE.
