### ISSUE TITLE
Investigate edge caching for dynamic tiling

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-backend#83]
## Description
During a conversation with @sharkinsspatial and Manil on dynamic tiling, Sean mentioned that they have implemented edge caching for the FIRMS project to deliver better performance when serving tiles from COGs. 

Notes from that discussion: https://docs.google.com/document/d/1L05XZIim55c-MXxrGneeustqNMNeheM3J5RkEED4jng/edit

## Acceptance criteria
- [ ] Using the FIRMS solution to caching tiles as a guide, propose a potential solution for implementing into VEDA and review with team

## Potential follow-up tickets to create
- [ ] If there is a viable solution to go forward with, create tickets required to implement for the dashboard and review priority with @aboydnw 
- [ ] Create an Architecture Decision Record for any decisions/paths forward

**Comment by aboydnw** [comment]
@j08lue We created this a long time ago...I believe it would now be a Data Services ticket. Correct me if I am wrong, though!

**Comment by j08lue** [comment]
@aboydnw I think the reason why @abarciauskas-bgse tagged you for prioritization is because this is all about improving Dashboard user experience.

I think this is a very relevant improvement to consider: In my view, the sometimes a bit slow loading times of map tiles are most problematic in **discoveries**, because they look like a blog post and as a reader, you do not expect illustrations in a blog post to take several seconds to load. The story is different for a map interface, where some initial loading / warm-up time is more acceptable, IMO.

Caching gives a performance improvement on repeated requests. Since the requests for the discoveries are frequently repeated, that might work well there.

So I think it is great for our team to work on this - the gains will show in the Dashboard. This fits right into our goal https://github.com/NASA-IMPACT/veda-architecture/issues/127

**Comment by j08lue** [comment]
(@abarciauskas-bgse in the interest of having a tight definition of done for this ticket here, I suggest to limit this ticket to informing the potential of a solution and track any follow up (like ADR etc) in new tickets.)

**Comment by aboydnw** [comment]
@j08lue This is a really old ticket, before you were on board, so feel free to scrub my name from the checklists and shape it however makes the most sense :)

**Comment by j08lue** [comment]
Ah, I thought it resurfaced because of new knowledge / motion. I think it is a great suggestion, though, so let us see what happens to it. 😄

**Comment by j08lue** [comment]
Stale.
